# Generated by Django 3.1.6 on 2021-02-19 10:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122, null=True)),
                ('email', models.CharField(max_length=122, null=True)),
                ('age', models.IntegerField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('phone', models.CharField(max_length=122, null=True)),
                ('gender', models.CharField(choices=[('', 'Select Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=122, null=True)),
                ('address', models.TextField(max_length=255, null=True)),
                ('date', models.DateField(default=datetime.date.today, null=True)),
                ('serial', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(blank=True, max_length=122, null=True)),
                ('pres_date', models.DateField(auto_now_add=True)),
                ('appointment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_suggetion', models.CharField(blank=True, max_length=122, null=True)),
                ('prescription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(blank=True, max_length=122, null=True)),
                ('prescription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.prescription')),
            ],
        ),
    ]
