# Generated by Django 3.1.5 on 2021-02-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='Friday',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='Monday',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='Saturday',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='Sunday',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='Thursday',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='Tuesday',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='Wednesday',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
    ]
