# Generated by Django 3.1.6 on 2021-03-01 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210221_0103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'permissions': (('can_view_all', 'can_view_all'),)},
        ),
        migrations.AlterField(
            model_name='medicine',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.prescription'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.appointment'),
        ),
        migrations.AlterField(
            model_name='test',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.prescription'),
        ),
    ]
